Switch to OnceLock
hawkw/sharded-slab pull request #101
Opened 2024-12-02 08:01 UTC by Mehrbod2002

After issues report in lazy static target and rust releases in many crate switched to OnceLock to be steady mode with rust .

2024-12-07 07:30 UTC, paolobarbolini requested changes

2024-12-07 07:30 UTC, paolobarbolini commented on src/tid.rs
> +static REGISTRY: OnceLock<Registry> = OnceLock::new();
This should be possible without `OnceLock` by relying on:

* [`Mutex::new`](https://doc.rust-lang.org/1.83.0/std/sync/struct.Mutex.html#method.new) becoming _const_ in 1.63
* [`VecDeque::new`](https://doc.rust-lang.org/1.83.0/std/collections/struct.VecDeque.html#method.new) becoming _const_ in 1.68
* [`AtomicUsize::new`](https://doc.rust-lang.org/1.83.0/std/sync/atomic/struct.AtomicUsize.html#method.new) being _const_ since 1.24

`OnceLock` instead only got stabilized in 1.70 and has a small runtime overhead on every access (just like `lazy_static`)

2024-12-07 07:30 UTC, paolobarbolini commented on src/tid.rs
> +            .expect("msg")
As a side how is this supposed to work if every access [^1] panics on `None`, which is what you get if the `OnceLock` was not initialized yet?

[^1]: https://doc.rust-lang.org/1.83.0/std/sync/struct.OnceLock.html#method.get

2025-02-13 12:53 UTC, serprex commented on src/tid.rs
> +static REGISTRY: OnceLock<Registry> = OnceLock::new();
https://github.com/hawkw/sharded-slab/pull/108 looks like it has loom issues

2025-11-08 09:09 UTC, closed without merging